name: Weekly Pickles Report

on:
  # schedule:
  #   # 毎週月曜日の日本時間午前9時（UTC 00:00）に実行
  #   - cron: '0 0 * * 1'
  workflow_dispatch: # 手動実行のみ有効（スケジュール実行を有効にする場合は上記のコメントを外す）
    inputs:
      analysis_type:
        description: '分析タイプ'
        required: false
        default: 'domi'
        type: choice
        options:
          - domi
          - aga
      delivery_method:
        description: '配信方法'
        required: false
        default: 'console'
        type: choice
        options:
          - console
          - email_text
          - email_html
          - file_text
          - file_html
      debug_mode:
        description: 'デバッグモード（詳細ログを出力）'
        required: false
        default: false
        type: boolean
      days_back:
        description: '何日前からのデータを取得するか（テスト用）'
        required: false
        default: '7'
        type: string

jobs:
  send-report:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    
    - name: Set up Python
      run: uv python install 3.12
    
    - name: Install dependencies
      run: uv sync --frozen
    
    - name: Run Pickles analysis
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
        EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
      run: |
        # 手動実行時は入力値を使用、スケジュール実行時はデフォルト値を使用
        ANALYSIS="${{ github.event.inputs.analysis_type || 'domi' }}"
        DELIVERY="${{ github.event.inputs.delivery_method || 'email_html' }}"
        
        # デバッグモードの確認
        if [[ "${{ github.event.inputs.debug_mode }}" == "true" ]]; then
          echo "=== Debug Mode Enabled ==="
          echo "Analysis Type: $ANALYSIS"
          echo "Delivery Method: $DELIVERY"
          echo "Environment variables status:"
          echo "NOTION_API_KEY: ${NOTION_API_KEY:+SET}"
          echo "NOTION_PAGE_ID: ${NOTION_PAGE_ID:+SET}"
          echo "OPENAI_API_KEY: ${OPENAI_API_KEY:+SET}"
          echo "EMAIL_USER: ${EMAIL_USER:+SET}"
          echo "EMAIL_PASS: ${EMAIL_PASS:+SET}"
          echo "EMAIL_TO: ${EMAIL_TO:+SET}"
          echo "EMAIL_HOST: ${EMAIL_HOST:+SET}"
          echo "EMAIL_PORT: ${EMAIL_PORT:+SET}"
          echo "========================"
        fi
        
        # days_backパラメータの処理
        DAYS_PARAM=""
        if [[ -n "${{ github.event.inputs.days_back }}" ]]; then
          DAYS_PARAM="--days ${{ github.event.inputs.days_back }}"
        fi
        
        uv run python main.py --analysis "$ANALYSIS" --delivery "$DELIVERY" $DAYS_PARAM